### PR TITLE
Profile page

### PR DESCRIPTION
**Pull request by Hiroshi18**
This PR create the profile page and its components header, feed score

## Issue 
Profile page

## Description

To test this go to the:
/profile
there you can see a default profile
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by filipetoyoshima — CHANGES_REQUESTED** [review]
image

It is a lot different from the prototype, isn't it?

**Review by filipetoyoshima — CHANGES_REQUESTED** [review]
## Elements over header
### Problem

Scrolling up the elements makes them pass over the header, which is not correct.
image

### Solution
Try to set the `z-index` property to create the expected result.

## NavBar over elements
When reaching the bottom of the page, is not possible to see all the content because NavBar stays over it.
image

This is strange, cause 5be77a9e38803d605362cde54bcd272a128a6e15 should fix this.

---------

**Comment by Hiroshi18** [comment]
> This is strange, cause [5be77a9](https://github.com/PI2-prensa-de-latas/software-frontend/commit/5be77a9e38803d605362cde54bcd272a128a6e15) should fix this.

adding it to the style in the feed fixed it but it is still strange

**Review by filipetoyoshima — APPROVED** [review]
Nice screen!

**Comment by Hiroshi18** [comment]
S2

**Pull request merged**
